language: php
php:
- '7.0'
node_js:
- '0.10'
before_install:
- echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- gem install sass
- npm install
install:
- composer install --no-dev
- grunt
script: 
- tar cvzf /tmp/mongolo.tar.gz . --exclude='.sass-cache' --exclude='node_modules' --exclude='.travis.yml' --exclude='.git' --exclude='screenshots'
deploy:
  provider: releases
  api_key:
    secure: BqWslF4tmP6c4Qxr7HU71xmFwCFhOh5oYpGeIaZ4daDPspTgz6GFMkrL/qRtAmtAczcrounpmX+uehh1MENABuZ+Ha8GiSWdejhlN3ZyA1cgomOmFuNSDliOe/wVhBSL438A/vx9r6tt0uXirxjJEzBwaQCYOI1s5YOvMPOn/fpRwDzU+9FbSCyJv5Jbp9FBZ2fif7Fp8zmuVEXcYXGFTagqMD7WAmQ+Qx0QhD7xz4vM/QZXoPQU3TgOwBKvFFFNndeY5fxj8EQRFcHzBCwB8nR78RZC00hPS7kqHVzJ9CxcDHTJxnpi3mxqSrDRjt1LGhRsLHwVofCHV3D2bA0hx1q5rgWpXIJaXZyZn0AhklPV1seiXKa400QYKTyrdjHopQy+1u/43H3h5GY4ecjS/cL9mQhcyCCOni0JPuRrIi8g+HU3GXACx0Vkn3rX6H7rv+EQdtk2Qbq1I5MmCcTYYGNHGCrurPDxjxsiGZ/F2KCaR8eGOK+F0Z9dKb6/jUGgJVpZqGNSarBcCjPTxaEfxrtcVv3TrpBWz2QObjyZe/KHNbosad8BkLVlSxdpAO3198GQwQ4MzPLP/Q6iCKb9jeZg8a1F/GgiUXO1djRqdl7wGrPZM437qaneQuqq1QxXTy+cyxTliPOTi9q0K7RgQsE4mHtYb2+fRuJ2CVNPnYw=
  file: /tmp/mongolo.tar.gz
  on:
    repo: tetreum/mongolo
    branch: master
after_deploy:
- "echo 'deployed!'"
